import = [
  "~/.config/alacritty/themes/themes/citylights.toml"
]

[shell]
program = "/bin/zsh"  # Example for Linux/BSD/macOS
args = ["-l"]

[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true

[font.normal]
family = "MesloLGM Nerd Font Mono"
style = "Regular"
[font.bold]
family = "MesloLGM Nerd Font Mono"
style = "Bold"
[font.bold_italic]
family = "MesloLGM Nerd Font Mono"
style = "Bold Italic"
[font.italic]
family = "MesloLGM Nerd Font Mono"
style = "Italic"

[window]
option_as_alt = "Both"
startup_mode = "Maximized"
